// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/weather-home/Ambient.tsx": () => import("../components/mockups/weather-home/Ambient.tsx"),
  "./components/mockups/weather-home/Decision.tsx": () => import("../components/mockups/weather-home/Decision.tsx"),
  "./components/mockups/weather-home/Letter.tsx": () => import("../components/mockups/weather-home/Letter.tsx")
};
